/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as EnvironmentsRouteImport } from './routes/environments'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiToolsRouteImport } from './routes/ai-tools'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsRoute = EnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiToolsRoute = AiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-tools': typeof AiToolsRoute
  '/analytics': typeof AnalyticsRoute
  '/builder': typeof BuilderRoute
  '/docs': typeof DocsRoute
  '/environments': typeof EnvironmentsRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-tools': typeof AiToolsRoute
  '/analytics': typeof AnalyticsRoute
  '/builder': typeof BuilderRoute
  '/docs': typeof DocsRoute
  '/environments': typeof EnvironmentsRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-tools': typeof AiToolsRoute
  '/analytics': typeof AnalyticsRoute
  '/builder': typeof BuilderRoute
  '/docs': typeof DocsRoute
  '/environments': typeof EnvironmentsRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-tools'
    | '/analytics'
    | '/builder'
    | '/docs'
    | '/environments'
    | '/industries'
    | '/pricing'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-tools'
    | '/analytics'
    | '/builder'
    | '/docs'
    | '/environments'
    | '/industries'
    | '/pricing'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/ai-tools'
    | '/analytics'
    | '/builder'
    | '/docs'
    | '/environments'
    | '/industries'
    | '/pricing'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiToolsRoute: typeof AiToolsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BuilderRoute: typeof BuilderRoute
  DocsRoute: typeof DocsRoute
  EnvironmentsRoute: typeof EnvironmentsRoute
  IndustriesRoute: typeof IndustriesRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments': {
      id: '/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof EnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tools': {
      id: '/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiToolsRoute: AiToolsRoute,
  AnalyticsRoute: AnalyticsRoute,
  BuilderRoute: BuilderRoute,
  DocsRoute: DocsRoute,
  EnvironmentsRoute: EnvironmentsRoute,
  IndustriesRoute: IndustriesRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
